stages:
  - unittest
  - deploy-develop

unittest:
  stage: unittest
  allow_failure: true
  tags:
    - docker
  image: node:10-jessie
  services:
    - mongo:latest
  variables:
    MONGO_SERVER: mongodb://mongo:27017
    MONGO_SERVER_TEST: mongodb://mongo:27017
    DB: webapi_db_test
    DB_TEST: webapi_db_test
    #SECRET_HASH: ${SECRET}
    #CI_ENV: test
    #CONFIG_DIR: ./config/
    MONGO_URL: "${MONGO_SERVER}/${DB}"
    MONGO_URL_TEST: "${MONGO_SERVER_TEST}/${DB_TEST}"
  before_script:
    - apk update
    - apk upgrade
    - apk add git
    - apk add python make
  script:
    - npm install -d
    - npm update
    - npm prune
    - pwd
    - npm run lint
    - npm run test
  only:
    - ci_cd
  cache:
    paths:
    - node_modules/
  #artifacts:
  #  paths:
  #    - coverage/lcov-report/

deploy-develop-ovh:
  stage: deploy-develop
  image: node:10-jessie
  variables:
    SSH_PRIV_OVH_FILE: ".ssh/id_rsa"
  before_script:
    - apk --no-cache update
    - apk add gettext
    - apk add ansible
    - apk add openssh-client
    - mkdir -p $HOME/.ssh
    - chmod 700 $HOME/.ssh
    - ssh-keyscan -t rsa 176.31.163.48 >>$HOME/.ssh/known_hosts
    - echo $SSH_PRIV_OVH | base64 -d > $HOME/$SSH_PRIV_OVH_FILE
    - chmod 600 $HOME/$SSH_PRIV_OVH_FILE
  script:
    - pwd
    - cd ansible
    - cat deploy.yaml | envsubst > deploy-with-replaced-vars.yaml
    - ansible-playbook deploy-with-replaced-vars.yaml --inventory inventory.yaml --limit=host-ovh
  environment: develop
  only:
    - ci_cd
#  when: manual
