stages:
  - unittest
  - deploy-develop

unittest:
  stage: unittest
  allow_failure: true
  tags:
    - docker
  image: node:10-jessie
  services:
    - mongo:latest
  variables:
    PORT: 3000
    RESTFUL_API_PUBLIC_PORT: 3200
    MONGO_URL: mongodb://mongodb:27017/NodeAPI_test
    MONGO_URL_TEST: mongodb://mongodb:27017/NodeAPI_test
    NODE_ENV: development
    WEBAPINAME: "webapi"
    VERSION: 1
  before_script:
    - apt-get update
    - apt-get -y upgrade
    - apt-get -y install git
    - apt-get -y install python make
    - mongoimport --host mongo --db NodeAPI_test --collection audit_log --type json --file mongo-seed/audit_log.json --jsonArray
    - mongoimport --host mongo --db NodeAPI_test --collection book --type json --file mongo-seed/book.json --jsonArray
    - mongoimport --host mongo --db NodeAPI_test --collection collaborators --type json --file mongo-seed/collaborators.json --jsonArray
    - mongoimport --host mongo --db NodeAPI_test --collection collections_schemas --type json --file mongo-seed/collections_schemas.json --jsonArray
    - mongoimport --host mongo --db NodeAPI_test --collection crag --type json --file mongo-seed/crag.json --jsonArray
    - mongoimport --host mongo --db NodeAPI_test --collection system_tokens --type json --file mongo-seed/system_tokens.json --jsonArray
    - mongoimport --host mongo --db NodeAPI_test --collection tree --type json --file mongo-seed/tree.json --jsonArray
  script:
    - npm install -d
    - npm update
    - npm prune
    - pwd
    - npm install tslint
    - npm run lint
    - npm run unittest
  only:
    - develop
  cache:
    paths:
    - node_modules/
  #artifacts:
  #  paths:
  #    - coverage/lcov-report/

deploy-develop-ovh:
  stage: deploy-develop
  image: node:10-jessie
  variables:
    SSH_PRIV_OVH_FILE: ".ssh/id_rsa"
  before_script:
    - echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" >> /etc/apt/sources.list
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
    - apt-get -y update
    - apt-get -y install gettext
    - apt-get -y install ansible
    - apt-get -y install openssh-client
    - mkdir -p $HOME/.ssh
    - chmod 700 $HOME/.ssh
    - ssh-keyscan -t rsa 176.31.163.48 >>$HOME/.ssh/known_hosts
    - echo $SSH_PRIV_OVH | base64 -d > $HOME/$SSH_PRIV_OVH_FILE
    - chmod 600 $HOME/$SSH_PRIV_OVH_FILE
  script:
    - pwd
    - cd ansible
    - cat deploy.yaml | envsubst > deploy-with-replaced-vars.yaml
    - ansible-playbook deploy-with-replaced-vars.yaml --inventory inventory.yaml --limit=host-ovh
  environment: develop
  only:
    - develop
#  when: manual
