version: "3"
services:
  app:
    build: .
    restart: always
    networks:
      - nodeapp-network
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=${MONGO_URL}
      - MONGO_URL_TEST=${MONGO_URL_TEST}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - WEBAPINAME=${WEBAPINAME}
      - VERSION=${VERSION}   
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
  mongodb:
    container_name: mongodb
    image: mongo:latest    
    command: mongod --port 27018
    networks:
      - nodeapp-network
networks:
    nodeapp-network:
      driver: bridge