version: "3"
services:
  restful_api:
    build: .
    env_file: ${ENV:-.env}
    ports:
      - ${RESTFUL_API_PUBLIC_PORT}:${PORT}
    environment:
      - MONGO_URL=${MONGO_URL}
      - MONGO_URL_TEST=${MONGO_URL_TEST}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - WEBAPINAME=${WEBAPINAME}
      - VERSION=${VERSION}
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    networks:
      - my-proxy-net
    command: >
      /bin/sh -c "
        sleep 10;
        if [ -z $DEBUG ]; then 
          npm run start;
        else 
          npm run start;
        fi 
        "
networks:
  my-proxy-net:
    external:
      name: custom_network