version: "3"
services:
  restful_api:
    build: .
    restart: always
    networks:
      - nodeapp-network
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodbs
    environment:
      - MONGO_URL=${MONGO_URL}
      - MONGO_URL_TEST=${MONGO_URL_TEST}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - WEBAPINAME=${WEBAPINAME}
      - VERSION=${VERSION}   
      - COLLECTIONS_SCHEMAS=${COLLECTIONS_SCHEMAS}
      - COLLECTION_NAME=${COLLECTION_NAME}
      - AUDIT_LOG=${AUDIT_LOG}
      - SYSTEM_TOKENS=${SYSTEM_TOKENS}
    volumes:
      - .:/usr/src/app:z
      - /usr/src/app/node_modules
  mongodbs:
    container_name: mongodbs
    image: mongo:3.6.12  
    command: mongod --port 27017
    ports:
      - 27017
    networks:
      - nodeapp-network
networks:
    nodeapp-network:
      driver: bridge