version: "3"
services:
  app:
    build: .
    restart: always
    networks:
      - nodeapp-network
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest    
    command: mongod --port 27018
    networks:
      - nodeapp-network
networks:
    nodeapp-network:
      driver: bridge